#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

staged=$(git diff --cached --name-only --diff-filter=ACM);

hooksPath=$(git config --get core.hooksConfig)
hooksPath=${hooksPath:-$GIT_DIR/hooks}
echo "$staged" | lua $hooksPath/process.lua
status=$?
if [ $status != 0 ]; then
	exit $status
fi

echo "$staged" | while read -r line; do
	if [[ $line == *rbx[ml]x ]]; then
		git add "$line";
	fi
done

if [ -n "$(git status --porcelain)" ]; then 
	exit 0
else
	git status
	exit 1
fi
